// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMHG-yTVwSXRTkN0gVD_8rOGVj2Z80NNA',
    appId: '1:734248690610:web:12a584c9ef402170b77aab',
    messagingSenderId: '734248690610',
    projectId: 'petbuddy5',
    authDomain: 'petbuddy5.firebaseapp.com',
    storageBucket: 'petbuddy5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzxrtaDegKq7IUyNJNVdMlzuUqXoUy9Qo',
    appId: '1:734248690610:android:6faf84bc99c59469b77aab',
    messagingSenderId: '734248690610',
    projectId: 'petbuddy5',
    storageBucket: 'petbuddy5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxxaEXTzN_lJVt1yDs7Tm_Ad0FxTL68Nk',
    appId: '1:734248690610:ios:3e371aaf4910a7a1b77aab',
    messagingSenderId: '734248690610',
    projectId: 'petbuddy5',
    storageBucket: 'petbuddy5.appspot.com',
    iosClientId: '734248690610-9prshqfs35niau0itm7g6p0ac2d2sr9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.petBuddy',
  );
}
